apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zenic-flujo
  namespace: zenic-flujo
  labels:
    app.kubernetes.io/name: zenic-flujo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zenic-flujo
