apiVersion: v1
kind: Service
metadata:
  name: zenic-flujo
  namespace: zenic-flujo
  labels:
    app.kubernetes.io/name: zenic-flujo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: webhook
      port: 8081
      targetPort: webhook
      protocol: TCP
  selector:
    app.kubernetes.io/name: zenic-flujo
