"""
Zenic-Flujo — Esquemas Compartidos Pydantic v2
================================================

Modulo unificado de esquemas Pydantic v2 para usar tanto desde
Flask (web app) como desde FastAPI (api_v2).

Importacion recomendada:
    from src.schemas import WorkflowCreate, WorkflowResponse, ErrorResponse

Todos los modelos se re-exportan desde src.api_v2.models para
mantener compatibilidad hacia atras.
"""

from __future__ import annotations

from src.api_v2.models import (
    APIInfoResponse,
    APIKeyCreate,
    APIKeyResponse,
    AuthStatusResponse,
    ConnectorActionInfo,
    ConnectorConfigRequest,
    ConnectorExecuteRequest,
    ConnectorExecuteResponse,
    ConnectorInfo,
    ConnectorPublishRequest,
    ConnectorSearchRequest,
    ConnectorSearchResponse,
    ConnectorSearchResult,
    ConnectorTestRequest,
    ConnectorTestResponse,
    DashboardStatsResponse,
    ErrorResponse,
    HealthResponse,
    LicenseInfoResponse,
    LoginResponse,
    MarketplaceCategory,
    MarketplaceStats,
    MFAEnableRequest,
    MFAVerifyRequest,
    NLUCompileRequest,
    NLUCompileResponse,
    NLUDryRunRequest,
    NLUDryRunResponse,
    NLUTrainingStatus,
    NLUTrainRequest,
    NLUTrainResponse,
    NLUUnderstandRequest,
    NLUUnderstandResponse,
    PaginatedResponse,
    PaginationParams,
    RefreshTokenRequest,
    StatusDeletedResponse,
    StatusResponse,
    StatusUpdatedResponse,
    TenantCreate,
    TenantFeatureToggle,
    TenantResponse,
    TenantUpdate,
    TenantUserCreate,
    TenantUserResponse,
    TokenRequest,
    TokenResponse,
    UserResponse,
    WorkflowCreate,
    WorkflowEvent,
    WorkflowExecutionDetail,
    WorkflowExecutionRequest,
    WorkflowExecutionResponse,
    WorkflowExportResponse,
    WorkflowImportRequest,
    WorkflowResponse,
    WorkflowUpdate,
)

__all__ = [
    "APIInfoResponse",
    "APIKeyCreate",
    "APIKeyResponse",
    "AuthStatusResponse",
    "ConnectorActionInfo",
    "ConnectorConfigRequest",
    "ConnectorExecuteRequest",
    "ConnectorExecuteResponse",
    "ConnectorInfo",
    "ConnectorPublishRequest",
    "ConnectorSearchRequest",
    "ConnectorSearchResponse",
    "ConnectorSearchResult",
    "ConnectorTestRequest",
    "ConnectorTestResponse",
    "DashboardStatsResponse",
    "ErrorResponse",
    "HealthResponse",
    "LicenseInfoResponse",
    "LoginResponse",
    "MFAEnableRequest",
    "MFAVerifyRequest",
    "MarketplaceCategory",
    "MarketplaceStats",
    "NLUCompileRequest",
    "NLUCompileResponse",
    "NLUDryRunRequest",
    "NLUDryRunResponse",
    "NLUTrainRequest",
    "NLUTrainResponse",
    "NLUTrainingStatus",
    "NLUUnderstandRequest",
    "NLUUnderstandResponse",
    "PaginatedResponse",
    "PaginationParams",
    "RefreshTokenRequest",
    "StatusDeletedResponse",
    "StatusResponse",
    "StatusUpdatedResponse",
    "TenantCreate",
    "TenantFeatureToggle",
    "TenantResponse",
    "TenantUpdate",
    "TenantUserCreate",
    "TenantUserResponse",
    "TokenRequest",
    "TokenResponse",
    "UserResponse",
    "WorkflowCreate",
    "WorkflowEvent",
    "WorkflowExecutionDetail",
    "WorkflowExecutionRequest",
    "WorkflowExecutionResponse",
    "WorkflowExportResponse",
    "WorkflowImportRequest",
    "WorkflowResponse",
    "WorkflowUpdate",
]
