apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenic-flujo.fullname" . }}-secrets
  labels:
    {{- include "zenic-flujo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.WFD_SESSION_SECRET }}
  WFD_SESSION_SECRET: {{ .Values.secrets.WFD_SESSION_SECRET | quote }}
  {{- end }}
  {{- if .Values.secrets.WFD_LICENSE_SECRET }}
  WFD_LICENSE_SECRET: {{ .Values.secrets.WFD_LICENSE_SECRET | quote }}
  {{- end }}
  {{- if .Values.secrets.WFD_ENCRYPTION_MASTER_KEY }}
  WFD_ENCRYPTION_MASTER_KEY: {{ .Values.secrets.WFD_ENCRYPTION_MASTER_KEY | quote }}
  {{- end }}
